### ISSUE TITLE
false dichotomy

### ISSUE THREAD

**Issue by thematrixiam** [conormccauley1999/DichotomyTests#1]
Ironically, the largest issue with this test is that they are all false dichotomies.

You also have issues of double barrelled. Where you're answer is not defined enough and are actually asking multiple avenues at once. 

Why not do it the way professionals would? 

Create weighted matrix survey and use something like a spider web diagram? 

Certain things are also useful, such as:
Other
Not Applicable
Prefer not to answer
Etc

Having "Other" is a good way to determine if you are missing something, and can provide you with more information. 

Allowing multiple answers for a question that the user can score with a weight system is also beneficial. 

--------------------------------------
eg.

Rate the following in terms of importance morally:

or

Rate the following in terms of importance ethically:

or

Rate the following in terms of importance emotionally:

or

Rate the following in terms of importance pragmatically:

---------------------------------------------

Notice that I also broke up the false dichotomy that was also an issue. Things could have importance from different lenses. 

That said... All of those things I listed are not necessary. But some of them would help provide a clearer picture.

**Comment by conormccauley1999** [comment]
I'll look into resolving the issues, and if practical, implementing the improved questioning and scoring systems.

**Comment by thematrixiam** [comment]
> Why? [this](http://grahamberrisford.com/AM%204%20System%20theory/Philosophical%20dichotomies.htm) at least loosely correlates with the proposed dichotomies.

It all depends on how accurate you want to be. 
Also that link doesn't seem remotely rooted in Psychology. 

This "test" is a survey. 

Survey's are covered by the field of Psychology, specifically Statistics and Analysis.

Materialism isn't even remotely tied to Spirituality. That's like saying you're 67% bear and 33% taxes. So, no, I do not see how these are even dichotomies.


> The questions are not double barrelled in the original sense, but the answers influence sometimes more than one value and are thus kinda coupled. but maybe it is impossible to have only entirely isolated questions?

There are instances where your answer could mean multiple things. On the one hand it could be very moral, on the other hand the same answer could be very immoral.

> I figure this is an informal test.

Yes. It is. 

At which point it begs the question, why do it at all. My child can make a cardboard box and call it a house. But I wouldn't want to sleep in it. 

> probably


> I don't see which ones you broke up.

Ethically, morally, emotionally, pragmatically.

**Comment by conormccauley1999** [comment]
> Also that link doesn't seem remotely rooted in Psychology

This is a philosophical test. It has nothing to do with psychology.

> At which point it begs the question, why do it at all. My child can make a cardboard box and call it a house. But I wouldn't want to sleep in it.

Because it's good fun - both to make the test and to take it. If you were looking for a more scientifically grounded test then I'm sorry to disappoint but this isn't it - nor does it claim to be.

**Comment by sgitkene** [comment]
Thanks for taking the time to write detailed responses. I will try my best to be as diligent.

> > Why? [this](http://grahamberrisford.com/AM%204%20System%20theory/Philosophical%20dichotomies.htm) at least loosely correlates with the proposed dichotomies.
> 
> It all depends on how accurate you want to be.
> Also that link doesn't seem remotely rooted in Psychology.

It is the first source I found on the issue. Maybe there are better sources, if you find any more, especially conflicting ones, you could post them. This quiz/test is probably not about psychology. It calls itself a philosophical quiz.

> This "test" is a survey.

tell me, where are the survey results saved? it seems to me the data is only for the user and not sent back to the server. thus no data is aggregated, making this entirely a "decision helper tool" ("test") and not a survey.

> _Surveys_ are covered by the field of Psychology, specifically Statistics and Analysis.

Only because statistics and analysis is covered in any respectable psychology education doesn't make it a subfield of psychology. I would call them more of a subfield of mathematics. Surveys may be covered by psychology, I don't know. but again, this is not a survey, but a test.

> Materialism isn't even remotely tied to Spirituality. That's like saying you're 67% bear and 33% taxes. So, no, I do not see how these are even dichotomies.

Materialism, as the school of thought that teaches everything is based on the material world and excludes any "higher entities", may very well be seen as the antithesis to spirituality, which supposes there are "higher entities" or even suppose the world is made up entirely of those.

> > The questions are not double barrelled in the original sense, but the answers influence sometimes more than one value and are thus kinda coupled. but maybe it is impossible to have only entirely isolated questions?
> 
> There are instances where your answer could mean multiple things. On the one hand it could be very moral, on the other hand the same answer could be very immoral.

the test does not seem to impose any moral framework. if an answer seems immoral to you, that tells you something about your own intrinsic moral compass, not about the question.

> > I figure this is an informal test.
> 
> Yes. It is.
> 
> At which point it begs the question, why do it at all. My child can make a cardboard box and call it a house. But I wouldn't want to sleep in it.

To your posed question: I could see how someone would use this to find out more about their own worldviews, or which parts of philosophy they might be drawn to. Or even publicly take the test to "show off" or [entertain](https://www.youtube.com/watch?v=Ei8bOkwN6cQ)

> > probably
> 

looking at the source, how you answer will influence the resulting inclination towards a philosophy, often more than one.

> > I don't see which ones you broke up.
> 
> Ethically, morally, emotionally, pragmatically.

but that is what the test tries to find out: do you look at things __more__ through a pragmatic lens, or are you listening more for your emotions or gut feeling? Do you suppose an ethical framework or are you more inclined to finding out what is "right" yourself, or do you even suppose that there is a "right" thing? These concepts are looked at in various philosophies. there is probably no "right" answer to any of the questions, but most could probably carry a discussion.

**Comment by thematrixiam** [comment]
Just my advice.

Do with it what you will.

My degree is in Psychology. And I have extensive courses in stats and survey building.

https://en.wikipedia.org/wiki/Survey_methodology

To give a feedback, such as an IQ score, or a Philosophical rank on a Dichotomy line, there needs to be an accurate understanding of measurements. What are you measuring. What is the response giving you..

It is all fun and games to argue for the sake of arguing. That said, I don't pick fights with the mechanic that stops by the side of the road to help someone with a lawnmower problem. He very well may have valid points about a lawnmower, even though he fixes cars. 

That said, it's an appeal to authority to say that you should just take my word for it... Which is why I would say, go and look at google. 

Maybe my problem is I am coming of as the dad that helps his kid with his science project... after all, maybe this test is all fun an games and isn't supposed to actually do anything... Basically, a magic 8 ball.

Have at 'er. 

No point in me re-hashing what has already been said. 

I care about truth... Find it how ever you deem fit. It need not be come from me. I am wrong all the time. 
Maybe I am wrong when I say that I don't think Philosophy spends millions of dollars on developing testing techniques.
